<?php

/**
 * CLIENT
 */
define('ACCESS_CLIENT_USER', 'CLIENT_USER');
define('ACCESS_CLIENT_RESOURCE', 'CLIENT_RESOURCE');
define('ACCESS_CLIENT_COMMENTAIRE', 'CLIENT_COMMENTAIRE');
define('ACCESS_CLIENT_PROGRESS', 'CLIENT_PROGRESS');
define('ACCESS_CLIENT_STATISTIQUE', 'CLIENT_STATISTIQUE');

/**
 * ADMIN
 */
define('ACCESS_ADMIN_PROFILES_ACCESS', 'ADMIN_PROFILES_ACCESS');
define('ACCESS_ADMIN_CATEGORIES', 'ADMIN_CATEGORIES');
define('ACCESS_ADMIN_BADGE', 'ADMIN_BADGE');
define('ACCESS_ADMIN_QUIZ', 'ADMIN_QUIZ');
define('ACCESS_ADMIN_STATISTIQUE', 'ADMIN_STATISTIQUE');
define('ACCESS_ADMIN_USER', 'ADMIN_USER');