<?php

/**
 * CLIENT
 */
define('ACCESS_CLIENT_USER', 'CLIENT_USER');
define('ACCESS_CLIENT_RESOURCE', 'CLIENT_RESOURCE');
define('ACCESS_CLIENT_CATEGORIE', 'CLIENT_CATEGORIE');
define('ACCESS_CLIENT_QUIZ', 'CLIENT_QUIZ');
define('ACCESS_CLIENT_COMMENT', 'CLIENT_COMMENT');
define('ACCESS_CLIENT_PROGRESS', 'CLIENT_PROGRESS');
define('ACCESS_CLIENT_STATISTIQUE', 'CLIENT_STATISTIQUE');

/**
 * ADMIN
 */
define('ACCESS_ADMIN_PROFILES_ACCESS', 'ADMIN_PROFILES_ACCESS');
define('ACCESS_ADMIN_USER', 'ADMIN_USERS_ACCESS');
define('ACCESS_ADMIN_COMMENTS', 'ADMIN_COMMENTS_ACCESS');
define('ACCESS_ADMIN_CATEGORIES', 'ADMIN_CATEGORIES_ACCESS');
define('ACCESS_ADMIN_RESOURCES', 'ADMIN_RESOURCES_ACCESS');
define('ACCESS_ADMIN_BADGE', 'ADMIN_BADGES_ACCESS');
define('ACCESS_ADMIN_QUIZ', 'ADMIN_QUIZZES_ACCESS');
define('ACCESS_ADMIN_STATISTIQUE', 'ADMIN_STATISTIQUES_ACCESS');